# Super user permission
sudo: required
services:
  - docker

before_install:
  # Tag the image and the repo name
  - docker build -t samczar/docker-react -f Dockerfile.dev .

script:
  - docker run samczar/docker-react yarn run test -- --coverage
